version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_bot_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - USE_MONGODB=${USE_MONGODB}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LOG_DIR=/app/logs
    env_file:
      - .env
    volumes:
      - /tmp/logs:/app/logs
      - /tmp/data:/app/data
      - /tmp/data/cache:/app/data/cache
      - ${MODELS_LOCATION}:/app/models
      - /tmp/audios:/tmp/audios
      - /tmp/videos:/tmp/videos
    networks:
      - cine-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]

networks:
  cine-network:
    external: true