"""Configuration data for Unsplash image fetcher (synonyms and stopwords)."""

UNSPLASH_SYNONYMS = {
    "protesta": ["manifestación", "reclamo", "activismo"],
    "tecnología": ["innovación", "dispositivo", "futuro"],
    "guerra": ["conflicto", "militar", "soldado"],
    "economía": ["finanzas", "mercado", "dinero"],
    "clima": ["medio ambiente", "naturaleza", "tormenta"],
    "salud": ["hospital", "médico", "enfermedad"],
    "educación": ["escuela", "estudiante", "aula"],
    "política": ["gobierno", "elecciones", "parlamento"],
    "energía": ["electricidad", "solar", "infraestructura"],
    "crimen": ["policía", "justicia", "investigación"],
}

STOPWORDS = {
    "el",
    "la",
    "los",
    "las",
    "un",
    "una",
    "unos",
    "unas",
    "de",
    "del",
    "en",
    "y",
    "o",
    "que",
    "es",
    "son",
    "se",
    "con",
    "por",
    "para",
    "sin",
    "sobre",
    "bajo",
    "entre",
    "hacia",
    "desde",
    "esta",
    "este",
    "estos",
    "estas",
    "ese",
    "esa",
    "esos",
    "esas",
    "aquel",
    "aquella",
    "como",
    "cuando",
    "donde",
    "más",
    "pero",
    "si",
    "no",
    "ya",
    "también",
    "muy",
    "todo",
    "todos",
    "todas",
    "al",
    "lo",
    "le",
    "les",
    "su",
    "sus",
    "ser",
    "estar",
    "hay",
    "tener",
    "hacer",
    "decir",
    "poder",
    "deber",
    "querer",
    "the",
    "a",
    "an",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "from",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "can",
    "shall",
    "it",
    "its",
    "this",
    "that",
    "these",
    "those",
    "not",
    "no",
}
