"""Configuration data for Unsplash image fetcher.

Contains all hardcoded lists for entity extraction, concept recognition,
and image query generation.
"""

UNSPLASH_SYNONYMS = {
    "protesta": ["manifestación", "reclamo", "activismo"],
    "tecnología": ["innovación", "dispositivo", "futuro"],
    "guerra": ["conflicto", "militar", "soldado"],
    "economía": ["finanzas", "mercado", "dinero"],
    "clima": ["medio ambiente", "naturaleza", "tormenta"],
    "salud": ["hospital", "médico", "enfermedad"],
    "educación": ["escuela", "estudiante", "aula"],
    "política": ["gobierno", "elecciones", "parlamento"],
    "energía": ["electricidad", "solar", "infraestructura"],
    "crimen": ["policía", "justicia", "investigación"],
}

STOPWORDS = {
    "el",
    "la",
    "los",
    "las",
    "un",
    "una",
    "unos",
    "unas",
    "de",
    "del",
    "en",
    "y",
    "o",
    "que",
    "es",
    "son",
    "se",
    "con",
    "por",
    "para",
    "sin",
    "sobre",
    "bajo",
    "entre",
    "hacia",
    "desde",
    "esta",
    "este",
    "estos",
    "estas",
    "ese",
    "esa",
    "esos",
    "esas",
    "aquel",
    "aquella",
    "como",
    "cuando",
    "donde",
    "más",
    "pero",
    "si",
    "no",
    "ya",
    "también",
    "muy",
    "todo",
    "todos",
    "todas",
    "al",
    "lo",
    "le",
    "les",
    "su",
    "sus",
    "ser",
    "estar",
    "hay",
    "tener",
    "hacer",
    "decir",
    "poder",
    "deber",
    "querer",
    "the",
    "a",
    "an",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "from",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "can",
    "shall",
    "it",
    "its",
    "this",
    "that",
    "these",
    "those",
    "not",
    "no",
}

ARTICULOS_CAPITALIZADOS = {
    "El",
    "La",
    "Los",
    "Las",
    "Un",
    "Una",
    "De",
    "En",
    "Por",
    "Para",
    "Con",
    "Sin",
    "The",
    "And",
    "For",
    "Of",
    "In",
    "To",
    "Is",
    "Are",
    "Was",
    "Were",
    "Be",
    "Been",
    "Have",
    "Has",
    "Had",
    "Do",
    "Does",
    "Did",
    "Will",
    "Would",
    "Could",
    "Should",
    "From",
    "With",
    "By",
    "At",
    "Or",
    "But",
    "Not",
    "You",
    "All",
    "Can",
    "Her",
    "One",
    "Our",
    "Out",
    "This",
    "That",
    "These",
    "Those",
    "It",
    "Hours",
    "Before",
    "News",
    "After",
    "What",
    "When",
    "Where",
    "Why",
    "How",
}

LUGARES_VISUALES = [
    "Rusia",
    "Ucrania",
    "Estados Unidos",
    "Washington",
    "Moscú",
    "Kiev",
    "China",
    "Pekín",
    "Europa",
    "Irán",
    "Teherán",
    "Israel",
    "Jerusalén",
    "Gaza",
    "Oriente Medio",
    "Casa Blanca",
    "Kremlin",
    "Pentágono",
    "OTAN",
    "ONU",
    "Naciones Unidas",
    "Congreso",
    "Parlamento",
]

CONCEPTOS_VISUALES = [
    "refinería",
    "fábrica",
    "edificio",
    "iglesia",
    "catedral",
    "mezquita",
    "manifestación",
    "protesta",
    "marcha",
    "conferencia",
    "cumbre",
    "reunión",
    "hospital",
    "escuela",
    "universidad",
    "estadio",
    "puerto",
    "aeropuerto",
    "misil",
    "cohetes",
    "tanque",
    "avión",
    "barco",
    "submarino",
    "presidente",
    "ministro",
    "papa",
    "pope",
    "líder",
    "general",
    "terremoto",
    "inundación",
    "incendio",
    "tormenta",
    "huracán",
]

EVENTOS_VISUALES = {
    "manifestación": "protest",
    "protesta": "protest",
    "marcha": "march",
    "reunión": "meeting",
    "cumbre": "summit",
    "conferencia": "conference",
    "ataque": "conflict",
    "guerra": "war",
    "conflicto": "conflict",
    "terremoto": "earthquake",
    "inundación": "flood",
    "incendio": "fire",
    "elección": "election",
    "elecciones": "election",
}
